name: Build and Deploy
on:
    push:
      branches:
      - main
    workflow_dispatch:

permission:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
    uses: actions/checkout@v3

    - name: Install and Build 
    run: |
      npm ci
      npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      witch:
        folder: dist/Walmart